# Ky tu dac biet
_spec_char 	= {	u'&': u'và',u'@': u'a còng', u'^': u'mũ', u'$': u'đô la', 
					u'%': u'phần trăm', u'*' : u'sao', u'+': u'cộng', u'>': u'dấu lớn', 
					u'<': u'dấu bé', u'=': u'bằng', u'/': u'trên'}

# Chu so
_number 		= {	0: u'không', 1: u'một', 2: u'hai', 3: u'ba', 4: u'bốn', 5: u'năm', 6: u'sáu', 7: u'bảy', 8: u'tám', 9: u'chín', 10: u'mười'}


# Don vi tien te
_currency 	= {	u'vnd': u'việt nam đồng', u'usd': 'đô la mỹ', u'eur': u'ơ rô'}


# Don vi do luong
_d_unit 		= {	u'km': u'ki lô mét', u'cm': u'xen ti mét', u'dm': u'đề xi mét', u'mm': u'mi li mét', u'nm':u'na nô mét', 
					u'm2' : u'mét vuông', u'm3' : u'mét khối',
					u'hz' : u'héc', u'm' : u'mét',
					u'h': u'giờ', u'p': u'phút', u's': u'giây'
					} 


# Don vi can nang
_w_unit 		= {u'kg': u'ki lô gam', u'g': 'gam'}


d = {'abc': ' công ty truyền thông abc',
 'adb': ' ngân hàng phát triển châu á',
 'anđt': ' an ninh điều tra',
 'atgt': ' an toàn giao thông',
 'atm': ' máy rút tiền tự động',
 'atnđ': ' áp thấp nhiệt đới',
 'attt': ' an toàn trật tự',
 'atttgt': ' an toàn trật tự giao thông',
 'atvstp': ' an toàn vệ sinh thực phẩm',
 'bbcvt': ' bộ bưu chính viễn thông',
 'bbt': ' ban biên tập',
 'bc': ' bán công',
 'bchcd': ' ban chỉ huy chiến dịch',
 'bchqs': ' bộ chỉ huy quân sự',
 'bchtw': ' ban chỉ huy trung ương',
 'bchtư': ' ban chỉ huy trung ương',
 'bcvt': ' bưu chính viễn thông',
 'bcđ': ' ban chỉ đạo',
 'bcđpctntư': ' ban chỉ đạo phòng chống tham nhũng trung ương',
 'bcđqg': ' ban chỉ đạo quốc gia',
 'bcđt': ' bưu chính điện tử',
 'bcđts': ' ban chỉ đạo tuyển sinh',
 'bcđđmđh': ' ban chỉ đạo đổi mới đại học',
 'bd': ' bình dương',
 'bgd': ' bộ giáo dục',
 'bgdđt': ' bộ giáo dục và đào tạo',
 'bgh': ' ban giám hiệu',
 'bgk': ' ban giám khảo',
 'bh': ' bảo hiểm',
 'bhl': ' ban huấn luyện',
 'bhv': ' ban huấn luyện',
 'bhxh': ' bảo hiểm xã hội',
 'bhyt': ' bảo hiểm y tế',
 'bhđc': ' bán hàng đa cấp ',
 'bidv': ' ngân hàng đầu tư và phát triển việt nam',
 'bk': ' bách khoa',
 'bks': ' ban kiểm soát',
 'blhs': ' bộ luật hình sự',
 'bp': ' biên phòng',
 'bql': ' ban quản lý',
 'bqlda': ' ban quản lý dự án',
 'bsc': ' công ty chứng khoán ngân hàng đầu tư & phát triển việt nam',
 'bt': ' bộ trưởng',
 'bta': ' hiệp định thương mại việt - mỹ',
 'btbnn': ' bảo trợ bệnh nhân nghèo',
 'btc': ' ban tổ chức',
 'bts': ' ban tuyển sinh',
 'btv': ' biên tập viên',
 'btvh': ' bổ túc văn hóa',
 'bv': ' bện viện',
 'bvtv': ' bảo vệ thực vật',
 'bvđk': ' bệnh viện đa khoa',
 'bx': ' bến xe',
 'bxl': ' bộ xử lý',
 'bđ': ' bóng đá',
 'bđn': ' bồ đào nha',
 'bđs': ' bất động sản',
 'bđvn': ' bóng đá việt nam',
 'cahn': ' công an hà nội',
 'cand': ' công an nhân dân',
 'catp': ' công an thành phố',
 'cb': ' cán bộ',
 'cbcc': ' cán bộ công chức',
 'cbcnv': ' cán bộ công nhân viên',
 'cbqlgd': ' cán bộ quản lý giáo dục',
 'ccb': ' cựu chiến binh',
 'cchc': ' cải cách hành chính',
 'cg': ' nhóm các nhà tài trợ cho việt nam',
 'chdc': ' cộng hòa dân chủ',
 'chdcnd': ' cộng hòa dân chủ nhân dân',
 'chlb': ' cộng hòa liên bang',
 'chnd': ' cộng hòa nhân dân',
 'ck': ' chứng khoán',
 'clb': ' câu lạc bộ',
 'cmnd': ' chứng minh nhân dân',
 'cncn': ' chi nhánh cấp nước',
 'cnh': ' công nghiệp hóa',
 'cnkt': ' công nhân kỹ thuật',
 'cnqsdđ': ' chứng nhận quyền sử dụng đất',
 'cnsh': ' công nghệ sinh học',
 'cntn': ' cử nhân tài năng ',
 'cntt': ' công nghệ thông tin',
 'cnv': ' công nhân viên',
 'cnvc': ' công nhân viên chức',
 'copd': ' bệnh phổi tắc nghẽn mãn tính',
 'cp': ' cổ phần',
 'cpe': ' hợp đồng lao động đầu tiên',
 'cph': ' cổ phần hóa',
 'cpp': ' đảng nhân dân cam pu chia',
 'cpsxtm': ' cổ phần xây dựng sản xuất thương mại',
 'cptd': ' cổ phiếu tự do',
 'cpttt': ' chậm phát triển trí tuệ',
 'cpxd': ' cấp phép xây dựng',
 'cqđt': ' cơ quan điều tra',
 'cscđ': ' cảnh sát cơ động',
 'csdc': ' cảnh sát dã chiến',
 'csdl': ' cơ sở dữ liệu',
 'csg': ' cảng sài gòn',
 'csgt': ' cảnh sát giao thông',
 'cshs': ' cảnh sát hình sự',
 'cskh': ' chăm sóc khách hàng',
 'cskt': ' cảnh sát kinh tế',
 'cskv': ' cảnh sát khu vực',
 'cspctpmt': ' cục cảnh sát phòng chống tội phạm ma túy',
 'cspk': ' công suất phản kháng',
 'csqlhc': ' cảnh sát quản lý hành chính',
 'cssd': ' đảng xã hội dân chủ cánh tả',
 'cssx': ' cơ sở sản xuất',
 'csvc': ' cơ sở vật chất',
 'csvl': ' cao su việt - lào ',
 'csvn': ' cộng sản việt nam',
 'csxh': ' chính sách xã hội',
 'csđn': ' cảnh sát đặc nhiệm',
 'csđt': ' cảnh sát điều tra',
 'csđtlx': ' cơ sở đào tạo lái xe',
 'csđttp': ' cảnh sát điều tra tội phạm',
 'csđttpmt': ' cảnh sát điều tra tội phạm ma túy',
 'ct': ' chính trị',
 'ctcc': ' công trình công cộng',
 'ctch': ' chấn thương chỉnh hình',
 'ctck': ' công ty chứng khoán',
 'ctclqg': ' chương trình chống lao quốc gia',
 'ctcn': ' công ty cấp nước',
 'ctcp': ' công ty cổ phần',
 'ctn': ' chuyển tiền nhanh',
 'ctsn': ' chấn thương sọ não',
 'cttc': ' cho thuê tài chính ',
 'ctth': ' chương trình truyền hình',
 'cttnhh': ' công ty trách nhiệm hữu hạn',
 'cttt': ' chương trình tiên tiến',
 'ctv': ' cộng tác viên',
 'ctxh': ' công tác xã hội ',
 'ctđ': ' chữ thập đỏ',
 'ctđl': ' công ty điện lực',
 'cv': ' chuyên viên',
 'cvpm': ' công viên phần mềm ',
 'cx': ' cư xá',
 'cđ': ' cao đẳng',
 'cđdc': ' chất độc da cam ',
 'cđsp': ' cao đẳng sư phạm',
 'cđv': ' cổ động viên',
 'dagtđt': ' dự án giao thông đô thị',
 'dcch': ' dân chủ cộng hòa',
 'dd': ' dân dụng',
 'ddvn': ' duyên dáng việt nam',
 'dhktcn': ' đại học kỹ thuật công nghệ',
 'dhs': ' du học sinh',
 'dl': ' du lịch',
 'dn': ' doanh nghiệp',
 'dnnn': ' doanh nghiệp nhà nước',
 'dnt': ' doanh nghiệp trẻ ',
 'dntn': ' doanh nghiệp tư nhân',
 'dnvn': ' doanh nghiệp việt nam',
 'dnvvn': ' doanh nghiệp vừa và nhỏ',
 'ds': ' dân số',
 'dt': ' dự tuyển',
 'dtht': ' dạy thêm học thêm',
 'dtqg': ' đội tuyển quốc gia',
 'dv': ' dịch vụ',
 'dvtmcm': ' dịch vụ thương mại cà mau',
 'dvtt': ' dịch vụ thông tin',
 'dvvl': ' dịch vụ việc làm',
 'eu': ' liên minh châu âu',
 'evn': ' công ty viễn thông điện lực',
 'fifa': ' liên đoàn bóng đá thế giới',
 'gatt': ' hiệp định chung về thuế quan và thương mại ',
 'gcmnd': ' giấy chứng minh nhân dân',
 'gcn': ' giấy chứng nhận',
 'gcnkqt': ' giấy chứng nhận kết quả thi ',
 'gcnqsd': ' giấy chứng nhận quyền sử dụng',
 'gcnqsdđ': ' giấy chứng nhận quyền sử dụng đất',
 'gcnqsdđơ': ' giấy chứng nhận quyền sử dụng đất ở',
 'gcnqsh': ' giấy chứng nhận quyền sở hữu',
 'gcnqshn': ' giấy chứng nhận quyền sở hữu nhà',
 'gcnqshnơ': ' giấy chứng nhận quyền sở hữu nhà ở',
 'gcnsk': ' giấy chứng nhận sức khỏe',
 'gcnđkkd': ' giấy chứng nhận đăng ký kinh doanh',
 'gcq': ' giấy chủ quyền',
 'gd': ' giáo dục',
 'gdgt': ' giáo dục giới tính ',
 'gdnn': ' giáo dục nghề nghiệp',
 'gdtx': ' giáo dục thường xuyên ',
 'gdđh': ' giáo dục dục đại học',
 'gdđt': ' giáo dục & đào tạo',
 'ghpgvn': ' giáo hội phật giáo việt nam',
 'gk': ' giáo khoa',
 'gkqt': ' chứng nhận kết quả thi',
 'gl': ' gia lai',
 'gmd': ' gái mại dâm ',
 'gp': ' giấy phép',
 'gpc': ' công ty dịch vụ viễn thông',
 'gplhđb': ' giấy phép lưu hành đặc biệt',
 'gplx': ' giấy phép lái xe',
 'gpnk': ' phép nhập khẩu',
 'gptm': ' giải phẫu thẩm mỹ',
 'gpxd': ' giấy phép xây dựng',
 'gs': ' giáo sư',
 'gsts': ' giáo sư tiến sỹ',
 'gstskh': ' giáo sư tiến sỹ khoa học',
 'gstt': ' giám sát trọng tài',
 'gt': ' giao thông',
 'gtcc': ' giao thông công chánh',
 'gtgt': ' giá trị gia tăng',
 'gtmt': ' giãn tĩnh mạch tinh',
 'gtvt': ' giao thông vận tải',
 'gv': ' giáo viên',
 'gvcn': ' giáo viên chủ nhiệm',
 'gvg': ' giáo viên giỏi ',
 'gvmn': ' giáo viên mầm non',
 'gvth': ' giáo viên tiểu học',
 'gvtn': ' giáo viên tình nguyện',
 'gđ': ' giám đốc',
 'gđt': ' gạch đồng tâm',
 'gđtla': ' gạch đồng tâm long an',
 'gđtt': ' giám đốc thông tin',
 'gđđh': ' giám đốc điều hành',
 'hagl': ' hoàng anh gia lai',
 'hb': ' học bổng',
 'hbv': ' vi rút viêm gan b',
 'hc': ' huy chương',
 'hcb': ' huy chương bạc',
 'hcm': ' hồ chí minh',
 'hctc': ' học chế tín chỉ ',
 'hctl': ' hội chợ triển lăm',
 'hcv': ' huy chương vàng',
 'hcvl': ' hội chợ việc làm ',
 'hcđ': ' huy chương đồng',
 'hd': ' hướng dẫn',
 'hdv': ' hướng dẫn viên',
 'hh': ' hoa hậu',
 'hhtg': ' hoa hậu thế giới',
 'hhvn': ' hoa hậu việt nam',
 'hk': ' học kỳ',
 'hkdd': ' hàng không dân dụng',
 'hkddvn': ' hàng không dân dụng việt nam',
 'hkhkt': ' hội khoa học kỹ thuật',
 'hkhktvn': ' hội khoa học kỹ thuật việt nam',
 'hktt': ' hộ khẩu thường trú',
 'hl': ' huấn luyện',
 'hlbđ': ' hoa lâm bình định',
 'hlqg': ' huấn luyện quốc gia',
 'hlttqg': ' trung tâm huấn luyện thể thao quốc gia',
 'hlv': ' huấn luyện viên',
 'hmnđ': ' hiến máu nhân đạo',
 'hn': ' hà nội',
 'hnd': ' hội nông dân',
 'hngđ': ' hôn nhân gia đình',
 'hnht': ' hội nghị hiệp thương ',
 'hnv': ' hội nhà văn',
 'hp': ' học phần',
 'hphn': ' hòa phát hà nội ',
 'hq': ' hàn quốc',
 'hqhp': ' hải quan hải phòng',
 'hqđt': ' hải quan điện tử',
 'hs': ' học sinh',
 'hsbc': ' học sinh bán công',
 'hsdpa': ' truy nhập gói đường xuống tốc độ cao',
 'hsg': ' học sinh giỏi',
 'hsgqg': ' học sinh giỏi quốc gia',
 'hsgqt': ' học sinh giỏi quốc tế',
 'hspt': ' học sinh phổ thông',
 'hssv': ' học sinh sinh viên',
 'hsv': ' hội sinh viên',
 'hsđkdt': ' hồ sơ đăng ký dự thi',
 'htcđ': ' học tập cộng đồng',
 'htxdvnn': ' hợp tác xã dịch vụ nông nghiệp',
 'hud': ' tổng công ty đầu tư phát triển nhà và đô thị ',
 'hv': ' học viên',
 'hvannd': ' học viện an ninh nhân dân',
 'hvbcvt': ' học viện bưu chính viễn thông',
 'hvch': ' học viên cao học',
 'hvcnbcvt': ' học viện công nghệ bưu chính viễn thông',
 'hvkhqs': ' học viện khoa học quân sự',
 'hvn': ' honda việt nam',
 'hvncl': ' hàng việt nam chất lượng',
 'hvnclc': ' hàng việt nam chất lượng cao',
 'hvnh': ' học viện ngân hàng',
 'hđ': ' hội đồng',
 'hđba': ' hội đồng bảo an liên hiệp quốc',
 'hđcd': ' hội đồng chức danh',
 'hđcdgs': ' hội đồng chức danh giáo sư',
 'hđcdgscs': ' hội đồng chức danh giáo sư cơ sở',
 'hđcdgsn': ' hội đồng chức danh giáo sư ngành',
 'hđcdgsnn': ' hội đồng chức danh giáo sư nhà nước',
 'hđct': ' hội đồng coi thi',
 'hđh': ' hệ điều hành',
 'hđkt': ' hợp đồng kinh tế',
 'hđlđ': ' hợp đồng lao động ',
 'hđndtp': ' hội đồng nhân dân thành phố',
 'hđnt': ' hội đồng nghệ thuật',
 'hđqt': ' hội đồng quản trị',
 'hđt': ' hội đồng thi ',
 'hđts': ' hội đồng tuyển sinh',
 'hđtt': ' hội đồng trọng tài',
 'hđtđ': ' hội đồng thẩm định',
 'hđxx': ' hội đồng xét xử',
 'hđđb': ' hội đồng đền bù',
 'hđđg': ' hội đồng định giá',
 'imf': ' quỹ tiền tệ quốc tế',
 'kbnn': ' kho bạc nhà nước',
 'kbs': ' kênh truyền hình tw hàn quốc',
 'kcb': ' khám chữa bệnh',
 'kcn': ' khu công nghiệp',
 'kcx': ' khu chế xuất',
 'kdc': ' khu dân cư',
 'kdcn': ' kiểu dáng công nghiệp',
 'kddv': ' kinh doanh dịch vụ',
 'kdhđc': ' kinh doanh hàng đa cấp',
 'kdl': ' khu du lịch',
 'kdn': ' kinh doanh nhà',
 'kdnpn': ' kinh doanh nhà phú nhuận',
 'kdđv': ' kiểm dịch động vật',
 'kh': ' kế hoạch',
 'khcn': ' khoa học công nghệ',
 'khkd': ' kế hoạch kinh doanh',
 'khkt': ' khoa học kỹ thuật',
 'khkthn': ' khoa học kỹ thuật hạt nhân',
 'khkths': ' khoa học kỹ thuật hình sự',
 'khktnn': ' khoa học kỹ thuật nông nghiệp',
 'khktnnmn': ' khoa học kỹ thuật nông nghiệp miền nam',
 'khls': ' khoa học lịch sử',
 'khtn': ' khoa học tự nhiên',
 'khxh': ' khoa học xãn hội',
 'khđt': ' kế hoạch đầu tư',
 'kk': ' khuyến khích',
 'kkt': ' khu kinh tế',
 'kl': ' kết luận',
 'klqg': ' kỷ lục quốc gia ',
 'klđt': ' kết luận điều tra',
 'kn': ' khuyến nông',
 'kntc': ' khiếu nại tố cáo',
 'kp': ' khu phố',
 'ks': ' khách sạn',
 'ksnd': ' kiểm sát nhân dân',
 'ksndtc': ' kiểm sát nhân dân tối cao',
 'kst': ' ký sinh trùng',
 'ksv': ' kiểm sát viên',
 'ktm': ' khu thương mại',
 'ktnn': ' kinh tế nhà nước',
 'ktqd': ' kinh tế quốc dân',
 'ktqdhn': ' kinh tế quốc dân hà nội',
 'kts': ' kiến trúc sư',
 'kttv': ' khí tượng thủy văn',
 'ktv': ' kỹ thuật viên',
 'ktx': ' ký túc xá',
 'kv': ' khu vực ',
 'kđcl': ' kiểm định chất lượng',
 'kđclgd': ' kiểm định chất lượng giáo dục',
 'kđs': ' khu đường sông',
 'kđt': ' khu đô thị',
 'kđtm': ' khu đô thị mới',
 'kđtntl': ' đô thị nam thăng long',
 'lb': ' liên bang',
 'lct': ' luật cạnh tranh',
 'ldp': ' đảng dân chủ tự do',
 'lh': ' liên hiệp',
 'lhp': ' liên hoan phim',
 'lhpn': ' liên hiệp phụ nữ',
 'lhq': ' liên hiệp quốc',
 'lhs': ' lưu học sinh',
 'lhtn': ' liên hiệp thanh niên',
 'lhtnvn': ' hội liên hiệp thanh niên việt nam',
 'll': ' lực lượng',
 'lllđ': ' lực lượng lao động',
 'ls': ' luật sư',
 'lsq': ' lãnh sự quán',
 'ltqđtd': ' lây truyền qua đường tình dục',
 'lđ': ' lao động',
 'lđbđ': ' liên đoàn bóng đá',
 'lđbđvn': ' liên đoàn bóng đá việt nam',
 'lđlđ': ' liên đoàn lao động',
 'lđtb': ' lao động thương binh',
 'lđtbxh': ' lao động thương binh xã hội',
 'mb': ' ngân hàng tmcp quân đội',
 'mbh': ' mũ bảo hiểm',
 'mhx': ' mùa hè xanh',
 'ms': ' mã số',
 'mt': ' môi trường',
 'mttq': ' mặt trận tổ quốc',
 'mttqvn': ' mặt trận tổ quốc việt nam',
 'mtxt': ' máy tính xách tay',
 'mtđt': ' máy tính điện tử',
 'nc': ' nghiên cứu',
 'ncc': ' nhà cung cấp',
 'nckh': ' nghiên cứu khoa học',
 'ncl': ' ngoài công lập',
 'ncs': ' nghiên cứu sinh',
 'ncto': ' hội đồng các tổ chức dệt may quốc gia mỹ ',
 'nctt': ' nghiên cứu thị trường',
 'nd': ' nhân dân',
 'ndc': ' trung tâm dữ liệu viễn thám quốc gia',
 'ndt': ' nhân dân tệ',
 'nh': ' ngân hàng',
 'nhcsxh': ' ngân hàng chính sách xã hội ',
 'nhctcn': ' ngân hàng công thương chi nhánh',
 'nhcthp': ' ngân hàng công thương hải phòng',
 'nhctvn': ' ngân hàng công thương việt nam',
 'nhk': ' đài truyền hình quốc gia nhật bản',
 'nhnn': ' ngân hàng nhà nước',
 'nhnno': ' ngân hàng nông nghiệp và phát triển nông thôn',
 'nhnnptnt': ' ngân hàng nông nghiệp và phát triển nông thôn',
 'nhnnvn': ' ngân hàng nhà nước việt nam',
 'nhnovn': ' ngân hàng nông nghiệp và phát triển nông thôn việt nam',
 'nhnt': ' ngân hàng ngoại thương',
 'nhrc': ' ủy ban nhân quyền quốc gia',
 'nhtm': ' ngân hàng thương mại',
 'nhtmcp': ' ngân hàng thương mại cổ phần',
 'nhtmnn': ' ngân hàng thương mại nhà nước',
 'nhtmqd': ' ngân hàng thương mại quốc doanh',
 'nhtq': ' ngân hàng trung ương trung quốc',
 'nhtsa': ' cục an toàn xa lộ quốc gia mỹ',
 'nhtw': ' ngân hàng trung ương ',
 'nhtư': ' ngân hàng trung ương ',
 'nhđa': ' ngân hàng đông á',
 'nhđt': ' ngân hàng đầu tư',
 'nhđtpt': ' ngân hàng đầu tư phát triển',
 'nhđá': ' ngân hàng đông á',
 'nk': ' nhập khẩu',
 'nkbv': ' nhiễm khuẩn bệnh viện',
 'nkkn': ' nam kỳ khởi nghĩa',
 'nknv': ' năng khiếu nghiệp vụ',
 'nkt': ' người khuyết tật',
 'nl': ' năng lượng',
 'nlmt': ' năng lượng mặt trời ',
 'nls': ' nông lâm sản',
 'nltt': ' năng lượng tái tạo',
 'nlđ': ' người lao động',
 'nmđ': ' nhà máy điện',
 'nn': ' nhà nước',
 'nncđdc': ' nạn nhân chất độc da cam',
 'nnptnt': ' nông nghiệp và phát triển nông thôn',
 'npp': ' nhà phân phối',
 'nq': ' nghị quyết',
 'nqd': ' ngoài quốc doanh',
 'ns': ' nghệ sỹ',
 'nsnd': ' nghệ sỹ nhân dân',
 'nsnn': ' ngân sách nhà nước ',
 'nst': ' nhiễm sắc thể',
 'nsưt': ' nghệ sỹ ưu tú',
 'ntbd': ' nghệ thuật biểu diễn',
 'ntd': ' nhà tuyển dụng',
 'ntk': ' nhà thiết kế',
 'nv': ' nhân viên',
 'nv1': ' nguyện vọng 1',
 'nv2': ' nguyện vọng 2',
 'nv3': ' nguyện vọng 3',
 'nvh': ' nhà văn hóa',
 'nvhtn': ' nhà văn hóa thanh niên ',
 'nxb': ' nhà xuất bản',
 'nxbgd': ' nhà xuất bản giáo dục',
 'nxbkhxh': ' nhà xuất bản khoa học xã hội',
 'nxbqđnd': ' nhà xuất bản quân đội nhân dân',
 'nxbtn': ' nhà xuất bản tự nhiên',
 'nxbvhtt': ' nhà xuất bản văn hóa nghệ thuật',
 'nđ': ' nghị định',
 'nđt': ' nhà đầu tư',
 'nđvn': ' người đẹp việt nam',
 'pc14': ' phòng cảnh sát điều tra tội phạm về trật tự xã hội',
 'pc15': ' phòng cảnh sát điều tra tội phạm về quản lý kinh tế và chức vụ',
 'pc16': ' phòng cảnh sát điều tra',
 'pc17': ' phòng cảnh sát phòng chống tội phạm ma tuý',
 'pcbl': ' phòng chống bão lụt',
 'pcbltkcn': ' phòng chống bão lụt và tìm kiếm cứu nạn',
 'pcbth': ' phổ cập bậc trung học',
 'pcc': ' phòng công chứng',
 'pccc': ' phòng cháy chửa cháy',
 'pcgd': ' phổ cập giáo dục',
 'pcgdbth': ' phổ cập giáo dục bậc trung học',
 'pcgdth': ' phổ cập giáo dục tiểu học',
 'pcgdthcs': ' phổ cập giáo dục trung học cơ sở',
 'pclbmn': ' phòng chống lụt bão miền nam',
 'pclbtw': ' phòng chống lụt bão trung ương',
 'pclbtư': ' phòng chống lụt bão trung ương',
 'pct': ' phó chủ tịch',
 'pcth': ' phổ cập tiểu học',
 'pcthcs': ' phổ cập trung học cơ sở',
 'pctn': ' phòng chống tệ nạn',
 'pctnxh': ' phòng chống tệ nạn xã hội',
 'pctpcnc': ' phòng chống tội phạm công nghệ cao',
 'pghh': ' phật giáo hòa hảo',
 'pgs': ' phó giáo sư',
 'pgđ': ' phó giám đốc',
 'phhs': ' phụ huynh học sinh',
 'pl': ' pháp luật',
 'plo': ' tổ chức giải phóng palestin',
 'pm': ' phần mềm',
 'pmu': ' ban quản lý dự án',
 'pn': ' phụ nữ',
 'pntr': ' quy chế thương mại bình thường vĩnh viễn',
 'pp': ' phương pháp',
 'ps': ' phóng sự',
 'ptcs': ' phổ thông cơ sở',
 'ptn': ' phòng thí nghiệm',
 'ptnt': ' phát triển nông thôn',
 'ptsc': ' công ty dịch vụ kỹ thuật dầu khí',
 'ptt': ' phó thủ tướng',
 'ptth': ' phổ thông trung học',
 'pttm': ' phẫu thuật thẩm mỹ',
 'pttt': ' phát triển trẻ thơ',
 'ptv': ' phát thanh viên',
 'pv': ' phóng viên',
 'py': ' phú yên',
 'qbltd': ' quĩ bảo lãnh tín dụng',
 'qc': ' quy chế',
 'qcdccs': ' quy chế dân chủ cơ sở',
 'qcgnhh': ' quy chế ghi nhãn hàng hóa',
 'qchq': ' quan chức hải quan',
 'qckdtxd': ' quy chế kinh doanh thép xây dựng',
 'qckt': ' quy chuẩn kĩ thuật',
 'qg': ' quốc gia',
 'qh': ' quốc hội',
 'qhtd': ' quan hệ tình dục',
 'qk': ' quân khu',
 'ql': ' quản lý',
 'qld': ' quản lý dược',
 'qlda': ' quản lý dự án',
 'qltt': ' quản lý thị trường',
 'qlđt': ' quản lý đào tạo',
 'qn': ' quảng ninh',
 'qsd': ' quyền sử dụng',
 'qsdđ': ' quyền sử dụng đất',
 'qtkd': ' quản trị kinh doanh',
 'qđ': ' quyết định',
 'qđnd': ' quân đội nhân dân',
 'rlc': ' rối loạn cương',
 'rlcd': ' rối loạn cương dương',
 'sars': ' hội chứng hô hấp cấp tính nặng',
 'sbd': ' số báo danh',
 'sbs': ' công ty chứng khoán ngân hàng sài gòn thương tín',
 'sd': ' sử dụng',
 'sdđ': ' sử dụng đất',
 'sdđnn': ' sử dụng đất nông nghiệp',
 'sg': ' sài gòn',
 'sgd': ' sở giáo dục',
 'sggp': ' sài gòn giải phóng',
 'sgk': ' sách giáo khoa',
 'sgt': ' saigontourist ',
 'sgtt': ' sài gòn tiếp thị ',
 'sgtvt': ' sở giao thông vận tải',
 'sh': ' sinh hoạt',
 'shnn': ' sở hữu nhà nước',
 'shtd': ' sinh hoạt tình dục',
 'shtt': ' sở hữu trí tuệ ',
 'sjc': ' công ty vàng bạc đá quý tp hồ chí minh',
 'sk': ' sân khấu',
 'skhcn': ' sở khoa học công nghệ',
 'skhcnmt': ' sở khoa học công nghệ và môi trường',
 'skhđt': ' sở kế hoạch và đầu tư',
 'skss': ' sức khỏe sinh sản',
 'slna': ' sông lam nghệ an',
 'smđh': ' sao mai điểm hẹn',
 'sn': ' sinh năm',
 'snn': ' sở nông nghiệp',
 'sp': ' sư phạm',
 'spkt': ' sư phạm kỹ thuật',
 'ss': ' sĩ số',
 'ssa': ' hiệp hội tôm miền nam nước mỹ',
 'stb': ' ngân hàng thương mại cổ phần sài gòn thương tín',
 'sv': ' sinh viên',
 'sv-hs': ' sinh viên học sinh',
 'svhs': ' sinh viên học sinh',
 'svnckh': ' sinh viên nghiên cứu khoa học',
 'svtn': ' sinh viên tình nguyện',
 'svvn': ' sinh viên việt nam',
 'svđ': ' sân vận động',
 'svđv': ' sao vàng đất việt ',
 'sx': ' sản xuất',
 'sxh': ' sốt xuất huyết',
 'syll': ' sơ yếu lý lịch',
 'sđh': ' sau đại học ',
 'sđk': ' số đăng ký',
 'sđnđ': ' sông đà nam định',
 'sđt': ' số điện thoại',
 'sđtla': ' sơn đồng tâm long an',
 'tacn': ' thức ăn chăn nuôi',
 'tand': ' tòa án nhân dân',
 'tandtc': ' tòa án nhân dân tối cao',
 'tbd': ' thái bình dương ',
 'tbktsg': ' thời báo kinh tế sài gòn ',
 'tbktvn': ' thời báo kinh tế việt nam',
 'tbmmn': ' tai biến mạch máu não',
 'tbt': ' tổng biên tập',
 'tbtt': ' thuê bao trả trước',
 'tbxh': ' thương binh xã hội',
 'tc': ' tài chính',
 'tcbvntd': ' tiêu chuẩn và bảo vệ người tiêu dùng',
 'tccn': ' trung cấp chuyên nghiệp',
 'tccs': ' tổ chức cơ sở',
 'tcdl': ' tổng cục du lịch ',
 'tchl': ' tuyệt chủng hàng loạt',
 'tchq': ' tổng cục hải quan',
 'tckh': ' tạp chí khoa học',
 'tckt': ' tài chính - kế toán',
 'tcmn': ' thủ công mỹ nghệ',
 'tcmr': ' tiêm chủng mở rộng ',
 'tcn': ' trung cấp nghề',
 'tcnn': ' tài chính nhà nước',
 'tcs': ' trịnh công sơn',
 'tct': ' tổng công ty',
 'tctd': ' tổ chức tín dụng',
 'tctt': ' trò chơi trực tuyến',
 'tcttmsg': ' tổng công ty thương mại sài gòn',
 'tcvn': ' tiêu chuẩn việt nam ',
 'tcvsg': ' thảo cầm viên sài gòn',
 'td': ' tình dục',
 'tdtt': ' thể dục thể thao',
 'tdttqg': ' thể dục thể thao quốc gia',
 'tdv': ' trình dược viên',
 'tfs': ' hãng phim truyền hình tphcm',
 'tg': ' thế giới',
 'tgpl': ' trợ giúp pháp lý',
 'tgđ': ' tổng giám đốc',
 'th': ' truyền hình',
 'thcb': ' trung học chuyên ban',
 'thcn': ' trung học chuyên nghiệp',
 'thcs': ' trung học cơ sở',
 'thcsnd': ' thực hiện chính sách nhà đất',
 'thcsnđ': ' thực hiện chính sách nhà đất',
 'thdl': ' trung học dân lập',
 'thgt': ' tín hiệu giao thông',
 'thkts': ' truyền hình kỹ thuật số',
 'thktsmđ': ' truyền hình kỹ thuật số mặt đất',
 'thpt': ' trung học phổ thông',
 'thqg': ' thương hiệu quốc gia',
 'ths': ' tín hiệu số',
 'thtt': ' truyền hình trực tiếp',
 'thvn': ' truyền hình việt nam',
 'thx': ' tân hoa xã',
 'tk': ' thiết kế',
 'tkcn': ' tìm kiếm cứu nạn',
 'tm': ' thương mại',
 'tmcp': ' thương mại cổ phần',
 'tmn': ' thép miền nam ',
 'tmv': ' công ty ôtô toyota việt nam',
 'tmđt': ' thương mại điện tử',
 'tn': ' thanh niên',
 'tncn': ' thu nhập cá nhân ',
 'tncs': ' thanh niên cộng sản',
 'tndn': ' thu nhập doanh nghiệp',
 'tngt': ' tai nạn giao thông',
 'tnhc': ' trinh nữ hoàng cung',
 'tnhh': ' trách nhiệm hữu hạn',
 'tnk': ' thuế nhập khẩu',
 'tnkq': ' trắc nghiệm khách quan',
 'tnln': ' thanh niên lập nghiệp',
 'tnmt': ' tài nguyên môi trường',
 'tnnd': ' tiếng nói nhân dân',
 'tnnt': ' thanh niên nông thôn',
 'tno': ' thanh niên online',
 'tns': ' tu nghiệp sinh',
 'tnsv': ' thanh niên sinh viên',
 'tnsvvn': ' thanh niên sinh viên việt nam',
 'tnt': ' tình nguyện trẻ',
 'tntn': ' thanh niên tình nguyện',
 'tntp': ' thiếu niên tiền phong',
 'tnv': ' tình nguyện viên',
 'tnvn': ' thanh niên việt nam',
 'tnxh': ' tệ nạn xã hội',
 'tnxk': ' thanh niên xung kích',
 'tnxp': ' thanh niên xung phong',
 'tnđh': ' tốt nghiệp đại học',
 'tnđt': ' thoát nước đô thị',
 'tpcn': ' thực phẩm chức năng',
 'tpct': ' thành phố cần thơ',
 'tpcđ': ' trái phiếu chuyển đổi',
 'tphcm': ' thành phố hồ chí minh',
 'tpo': ' tiên phong online',
 'tq': ' trung quốc',
 'tsdđ': ' tiền sử dụng đất',
 'tskh': ' tiến sỹ khoa học',
 'tsn': ' tân sơn nhất',
 'tt': ' trung tâm',
 'ttbdvh': ' trung tâm bồi dưỡng văn hóa',
 'ttbdvhng': ' trung tâm bồi dưỡng văn hóa ngoài giờ',
 'ttbvqtg': ' trung tâm bảo vệ quyền tác giả',
 'ttbyt': ' trang thiết bị y tế',
 'ttbđs': ' thị trường bất động sản',
 'ttck': ' thị trường chứng khoán',
 'ttcn': ' trung tâm cai nghiện',
 'ttcp': ' thủ tướng chính phủ',
 'ttct': ' thể thao cuối tuần',
 'ttdd': ' trung tâm dinh dưỡng',
 'ttdv': ' trung tâm dịch vụ',
 'ttdvvl': ' trung tâm dịch vụ việc làm',
 'ttg': ' thủ tướng',
 'ttgdck': ' trung tâm giao dich chứng khoán',
 'ttgdtx': ' trung tâm giáo dục thường xuyên',
 'ttgt': ' trật tự giao thông',
 'tth': ' thừa thiên huế',
 'tthtcđ': ' trung tâm học tập cộng đồng',
 'tthtsv': ' trung tâm hỗ trợ sinh viên',
 'ttk': ' tổng thư ký',
 'ttlt': ' thông tư liên tịch',
 'ttn': ' thanh thiếu niên',
 'ttnn': ' trung tâm ngoại ngữ',
 'tto': ' tuổi trẻ online',
 'ttqlkt': ' trật tự quản lý kinh tế',
 'ttth': ' trung tâm tin học',
 'tttm': ' trung tâm thương mại ',
 'ttton': ' thụ tinh trong ống nghiệm',
 'ttttn': ' trí thức trẻ tình nguyện',
 'ttvgt': ' trật tự viên giao thông',
 'ttvh': ' trung tâm văn hóa',
 'ttvn': ' thể thao việt nam',
 'ttxh': ' trật tự xã hội',
 'ttxvn': ' thông tấn xã việt nam',
 'ttyt': ' trung tâm y tế',
 'ttytdp': ' trung tâm y tế dự phòng',
 'ttđb': ' thuế tiêu thụ đặc biệt',
 'ttđm': ' trung tâm điện máy',
 'tv': ' ti vi',
 'tvhk': ' tiếp viên hàng không',
 'tvn': ' than việt nam',
 'tvqh': ' thường vụ quốc hội',
 'tvv': ' tư vấn viên',
 'tw': ' trung ương',
 'tx': ' thị xã',
 'tđ': ' từ điển',
 'tđbkvn': ' từ điển bách khoa việt nam',
 'tđc': ' tái định cư',
 'ubcknn': ' ủy ban chứng khoán nhà nước',
 'ubkt': ' uỷ ban kiểm tra',
 'ubmttq': ' ủy ban mạt trận tổ quốc',
 'ubmttqvn': ' ủy ban mặt trận tổ quốc việt nam',
 'ubndtp': ' ủy ban nhân dan thành phố',
 'ubtdtt': ' ủy ban thể dục thể thao',
 'ubtvqh': ' ủy ban thường vụ quốc hội ',
 'undp': ' chương trình phát triển liên hợp quốc',
 'unesco': ' khoa học và văn hóa của liên hiệp quốc',
 'unfpa': ' quỹ dân số liên hợp quốc',
 'unhcr': ' văn phòng cao ủy liên hợp quốc về người tỵ nạn',
 'unicef': ' quỹ nhi đồng liên hợp quốc',
 'unifil': ' lực lượng gìn giữ hòa bình của lhq tại miền nam libăng',
 'ut': ' ung thư',
 'uv': ' ủy viên',
 'uvbch': ' ủy viên ban chấp hành',
 'uvbct': ' ủy viên bộ chính trị',
 'vcb': ' ngân hàng ngoại thương việt nam',
 'vck': ' vòng chung kết',
 'vd': ' ví dụ',
 'vdc': ' công ty điện toán và truyền số liệu',
 'vff': ' liên đoàn bóng đá việt nam',
 'vh': ' văn hóa',
 'vhgdtntn': ' văn hóa giáo dục thanh niên thiếu niên',
 'vhgdttnnđ': ' văn hóa giáo dục thanh thiếu niên và nhi đồng',
 'vhnt': ' văn học nghệ thuật',
 'vhtt': ' văn hóa thông tin',
 'vks': ' viện kiểm sát',
 'vksnd': ' viện kiểm sát nhân dân',
 'vksndtc': ' viện kiểm sát nhân dân tối cao',
 'vl': ' vật lý',
 'vltk': ' võ lâm truyền kỳ',
 'vlxd': ' vật liệu xây dựng',
 'vn': ' việt nam',
 'vncc': ' tổng công ty xi măng việt nam',
 'vnm': ' vinamilk ',
 'vp': ' văn phòng',
 'vpcp': ' văn phòng chính phủ',
 'vpđd': ' văn phòng đại diện',
 'vqg': ' vườn quốc gia',
 'vs': ' vệ sinh',
 'vsp': ' xí nghiệp liên doanh vietsovpetro',
 'vt': ' viên thông',
 'vtv': ' đài truyền hình việt nam',
 'vysa': ' hội thanh niên sinh viên việt nam tại nhật bản',
 'vđ': ' vô địch',
 'vđqg': ' vô địch quốc gia',
 'vđv': ' vận động viên',
 'vđvqg': ' vận động viên quốc gia',
 'wb': ' ngân hàng thế giới',
 'wto': ' tổ chức thương mại thế giới',
 'xd': ' xây dựng',
 'xdcb': ' xây dựng cơ bản',
 'xdhk': ' xăng dầu hàng không',
 'xh': ' xã hội',
 'xhcn': ' xã hội chủ nghĩa',
 'xhh': ' xã hội hóa',
 'xk': ' xuất khẩu',
 'xklđ': ' xuất khẩu lao động',
 'xn': ' xí nghiệp',
 'xnk': ' xuất nhập khẩu',
 'xskt': ' xổ số kiến thiết',
 'xttm': ' xúc tiến thương mại',
 'xx': ' xét xử',
 'xđgn': ' xoá đói giảm nghèo',
 'ykvn': ' y khoa việt nam',
 'ytdp': ' y tế dự phòng',
 'ytế': ' y tế',
 'đatp': ' đông á - thép pomina ',
 'đb': ' đồng bằng',
 'đbdt': ' đồng bào dân tộc',
 'đbp': ' điện biên phủ',
 'đbqh': ' đại biểu quốc hội',
 'đbscl': ' đồng bằng sông cửu long',
 'đbtn': ' đại biểu thanh niên',
 'đbtsxb': ' đánh bắt thủy sản xa bờ',
 'đc': ' địa chỉ',
 'đcs': ' đảng cộng sản',
 'đcstq': ' đảng cộng sản trung quốc',
 'đcsvn': ' đảng cộng sản việt nam',
 'đd': ' đại diện',
 'đh': ' đại học',
 'đhbc': ' đại học bán công',
 'đhbk': ' đại học bách khoa',
 'đhbkhcm': ' đại học bách khoa thành phố hồ chí minh',
 'đhbkhn': ' đại học bách khoa hà nội',
 'đhbktphcm': ' đại học bách khoa thành phố hồ chí minh',
 'đhclc': ' đại học chất lượng cao',
 'đhcn': ' đại học công nghệ',
 'đhct': ' đại học cần thơ',
 'đhcđ': ' đại hội cổ đông',
 'đhdl': ' đại học dân lập',
 'đhgtvt': ' đại học giao thông vận tải',
 'đhhb': ' đại học hồng bàng',
 'đhhvn': ' đại học hàng hải việt nam',
 'đhkh': ' đại học khoa học',
 'đhkhtn': ' đại học khoa học tự nhiên',
 'đhkhtnhn': ' đại học khoa học tự nhiên hà nội',
 'đhkhxh': ' đại học khoa học xã hội',
 'đhkt': ' đại học kỹ thuật',
 'đhktcn': ' đại học kỹ thuật công nghệ',
 'đhktqd': ' đại học kinh tế quốc dân',
 'đhn': ' điện hạt nhân',
 'đhnt': ' đại học nha trang',
 'đhqg': ' đại học quốc gia',
 'đhqghn': ' đại học quốc gia hà nội',
 'đhsp': ' đại học sư phạm',
 'đhđcqt': ' đại học đẳng cấp quốc tế',
 'đhđd': ' đại học đông dương',
 'đhđn': ' đại học đà nẵng',
 'đk': ' đăng ký',
 'đkdt': ' đăng ký dự thi',
 'đkhk': ' đăng ký hộ khẩu',
 'đkkd': ' đăng ký kinh doanh',
 'đkkh': ' đăng ký kết hôn',
 'đkvn': ' điền kinh việt nam',
 'đkvđ': ' đương kim vô địch',
 'đkxt': ' đăng ký xét tuyển ',
 'đkđt': ' điện kế điện tử',
 'đl': ' đo lường',
 'đltp': ' điện kế điện tử ',
 'đmn': ' đá mỹ nghệ',
 'đn': ' đà nẵng',
 'đna': ' đông nam á',
 'đná': ' đông nam á',
 'đrl': ' điểm rèn luyện',
 'đs': ' đường sắt',
 'đsq': ' đại sứ quán',
 'đt': ' đào tạo',
 'đta': ' đồng tính ái',
 'đtb': ' điểm trung bình',
 'đtdđ': ' điện thoại di động',
 'đthvn': ' đài truyền hình việt nam',
 'đtla': ' đồng tính luyến ái',
 'đtlt': ' đào tạo liên thông',
 'đtnn': ' đầu tư nước ngoài',
 'đtqg': ' đội tuyển quốc gia',
 'đttx': ' đào tạo từ xa',
 'đttxqm': ' đào tạo từ xa qua mạng',
 'đtv': ' điều tra viên',
 'đtvhd': ' động thực vật hoang dã',
 'đtvn': ' đội tuyển việt nam',
 'đtxdcb': ' đầu tư xây dựng cơ bả',
 'đtđ': ' đái tháo đường',
 'đv': ' đoàn viên',
 'đvht': ' đơn vị học trình',
 'đvtn': ' đoàn viên thanh niên',
 'đvttn': ' đoàn viên thanh thiếu nhi',
 'đvưt': ' đoàn viên ưu tú',
 'đđ': ' động đất',
 'ưcv': ' ứng cử viên'}

# Tu dien viet tat
def short_dict():
	return d 
